theme: jekyll-theme-architect
title: Blargbot Custom Commands
repotitle: Blargbot Custom Commands
author: The BCC Team
authorurl: https://blargbotcc.tk/staff
url: https://blargbotcc.tk
image: https://blargbotcc.tk/files/bcc-logo.png
color: "#00a2ff"
google_analytics: UA-122079696-1
plugins:
  - jekyll-sitemap
